Same sacct thing for other workflows

diff --git a/.github/workflows/generate_reference_plots.yml b/.github/workflows/generate_reference_plots.yml
--- a/.github/workflows/generate_reference_plots.yml
+++ b/.github/workflows/generate_reference_plots.yml
@@ -42,8 +42,14 @@ jobs:
             DATAPATH="/wrk-kappa/group/spacephysics/analysator/CI/verification_sets/$(git rev-parse HEAD)"
             mkdir $DATAPATH
             touch $DATAPATH/.lockfile
-            sbatch -W -o testpackage_gen_verf.txt --job-name gen_verf_plots ./testpackage/run_testpackage_generate_verf_set.sh $DATAPATH
-
+            sbatch -W -o testpackage_gen_verf.txt --job-name gen_verf_plots ./testpackage/run_testpackage_generate_verf_set.sh $DATAPATH > jobid.txt
+            export JOBID=$(grep -Po '\d+' jobid.txt)
+            export SACCT_LOG=$(sacct -j $JOBID -o job,state,node | grep FAILED) 
+            if [[ $SACCT_LOG ]]; then
+              echo "Some job failed on a node"
+              echo $SACCT_LOG 
+              exit 1
+            fi
             cat testpackage_gen_verf.txt
 
             python ./testpackage/testpackage_get_job_error.py testpackage_gen_verf.txt
