Got rid of get_job_error in favor of getting the error via exit $? and sacct

diff --git a/.github/workflows/test_compare_images_full.yml b/.github/workflows/test_compare_images_full.yml
--- a/.github/workflows/test_compare_images_full.yml
+++ b/.github/workflows/test_compare_images_full.yml
@@ -50,25 +50,31 @@ jobs:
               exit 1
             fi 
             sbatch -W -o testpackage_run.txt --job-name gen_plots ./testpackage/run_testpackage_workflow.sh > jobid.txt
+            cat testpackage_run.txt
             export JOBID=$(grep -Po '\d+' jobid.txt)
             export SACCT_LOG=$(sacct -j $JOBID -o job,state,node | grep FAILED) 
             if [[ $SACCT_LOG ]]; then
-              echo "Some job failed on a node"
+              echo "Some job failed on a node, try to take a look at the slurm log."
               echo "$SACCT_LOG"
               exit 1
             fi
-            cat testpackage_run.txt
-            . CI_env/bin/activate
-            python ./testpackage/testpackage_get_job_error.py testpackage_run.txt
             
         - name: Comparing plotted data
           run: |
             export TMPDIR=$RUNNER_TEMP
             module load Python/3.10.4-GCCcore-11.3.0
             . CI_env/bin/activate
-            sbatch -W -o "testpackage_compare.txt" ./testpackage/run_compare.sh
+            sbatch -W -o "testpackage_compare.txt" ./testpackage/run_compare.sh > jobid1.txt
             cat testpackage_compare.txt
-            python ./testpackage/testpackage_get_job_error.py testpackage_compare.txt
+            export JOBID=$(grep -Po '\d+' jobid1.txt)
+            export SACCT_LOG=$(sacct -j $JOBID -o job,state,node | grep FAILED) 
+            if [[ $SACCT_LOG ]]; then
+              echo "Some job failed on a node, try to take a look at the slurm log."
+              echo "$SACCT_LOG" 
+              exit 1
+            fi
+
+
         - name: scancel dangling job upon cancellation
           if: cancelled()
           run: |
