Now the workflow should fail if job failed on the node

diff --git a/.github/workflows/test_compare_images.yml b/.github/workflows/test_compare_images.yml
--- a/.github/workflows/test_compare_images.yml
+++ b/.github/workflows/test_compare_images.yml
@@ -60,7 +60,12 @@ jobs:
             echo "Running $DIFFRESULT"
             sbatch -W -o testpackage_run.txt --job-name gen_plots ./testpackage/run_testpackage_workflow.sh $DIFFRESULT > jobid.txt
             export JOBID=$(grep -Po '\d+' jobid.txt)
-            sacct -j $JOBID -o job,state,node | grep FAILED
+            export SACCT_LOG=$(sacct -j $JOBID -o job,state,node | grep FAILED) 
+            if [[ $SACCT_LOG ]]; then
+              echo "Some job failed on a node"
+              echo $SACCT_LOG 
+              exit 1
+            fi
             cat testpackage_run.txt
             . CI_env/bin/activate
             python ./testpackage/testpackage_get_job_error.py testpackage_run.txt
